// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Protocol.proto
// Protobuf C++ Version: 6.33.4

#include "Protocol.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Protocol {

inline constexpr S2C_MatchSuccess::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        ds_ip_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        ds_port_{0} {}

template <typename>
PROTOBUF_CONSTEXPR S2C_MatchSuccess::S2C_MatchSuccess(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(S2C_MatchSuccess_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct S2C_MatchSuccessDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S2C_MatchSuccessDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~S2C_MatchSuccessDefaultTypeInternal() {}
  union {
    S2C_MatchSuccess _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S2C_MatchSuccessDefaultTypeInternal _S2C_MatchSuccess_default_instance_;

inline constexpr C2S_MatchRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        player_id_{0} {}

template <typename>
PROTOBUF_CONSTEXPR C2S_MatchRequest::C2S_MatchRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(C2S_MatchRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct C2S_MatchRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C2S_MatchRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~C2S_MatchRequestDefaultTypeInternal() {}
  union {
    C2S_MatchRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C2S_MatchRequestDefaultTypeInternal _C2S_MatchRequest_default_instance_;
}  // namespace Protocol
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_Protocol_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_Protocol_2eproto = nullptr;
const ::uint32_t
    TableStruct_Protocol_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Protocol::C2S_MatchRequest, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Protocol::C2S_MatchRequest, _impl_.player_id_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Protocol::S2C_MatchSuccess, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Protocol::S2C_MatchSuccess, _impl_.ds_ip_),
        PROTOBUF_FIELD_OFFSET(::Protocol::S2C_MatchSuccess, _impl_.ds_port_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::Protocol::C2S_MatchRequest)},
        {5, sizeof(::Protocol::S2C_MatchSuccess)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::Protocol::_C2S_MatchRequest_default_instance_._instance,
    &::Protocol::_S2C_MatchSuccess_default_instance_._instance,
};
const char descriptor_table_protodef_Protocol_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016Protocol.proto\022\010Protocol\"%\n\020C2S_MatchR"
    "equest\022\021\n\tplayer_id\030\001 \001(\005\"2\n\020S2C_MatchSu"
    "ccess\022\r\n\005ds_ip\030\001 \001(\t\022\017\n\007ds_port\030\002 \001(\005*>\n"
    "\tMessageId\022\013\n\007UNKNOWN\020\000\022\r\n\tREQ_MATCH\020\001\022\025"
    "\n\021RES_MATCH_SUCCESS\020\002b\006proto3"
};
static ::absl::once_flag descriptor_table_Protocol_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Protocol_2eproto = {
    false,
    false,
    189,
    descriptor_table_protodef_Protocol_2eproto,
    "Protocol.proto",
    &descriptor_table_Protocol_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_Protocol_2eproto::offsets,
    file_level_enum_descriptors_Protocol_2eproto,
    file_level_service_descriptors_Protocol_2eproto,
};
namespace Protocol {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL MessageId_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_Protocol_2eproto);
  return file_level_enum_descriptors_Protocol_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t MessageId_internal_data_[] = {
    196608u, 0u, };
// ===================================================================

class C2S_MatchRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<C2S_MatchRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(C2S_MatchRequest, _impl_._has_bits_);
};

C2S_MatchRequest::C2S_MatchRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, C2S_MatchRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.C2S_MatchRequest)
}
C2S_MatchRequest::C2S_MatchRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const C2S_MatchRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, C2S_MatchRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE C2S_MatchRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void C2S_MatchRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.player_id_ = {};
}
C2S_MatchRequest::~C2S_MatchRequest() {
  // @@protoc_insertion_point(destructor:Protocol.C2S_MatchRequest)
  SharedDtor(*this);
}
inline void C2S_MatchRequest::SharedDtor(MessageLite& self) {
  C2S_MatchRequest& this_ = static_cast<C2S_MatchRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL C2S_MatchRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) C2S_MatchRequest(arena);
}
constexpr auto C2S_MatchRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(C2S_MatchRequest),
                                            alignof(C2S_MatchRequest));
}
constexpr auto C2S_MatchRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_C2S_MatchRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &C2S_MatchRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<C2S_MatchRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &C2S_MatchRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<C2S_MatchRequest>(), &C2S_MatchRequest::ByteSizeLong,
              &C2S_MatchRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(C2S_MatchRequest, _impl_._cached_size_),
          false,
      },
      &C2S_MatchRequest::kDescriptorMethods,
      &descriptor_table_Protocol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull C2S_MatchRequest_class_data_ =
        C2S_MatchRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
C2S_MatchRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&C2S_MatchRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(C2S_MatchRequest_class_data_.tc_table);
  return C2S_MatchRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
C2S_MatchRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(C2S_MatchRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    C2S_MatchRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::C2S_MatchRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 player_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(C2S_MatchRequest, _impl_.player_id_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(C2S_MatchRequest, _impl_.player_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 player_id = 1;
    {PROTOBUF_FIELD_OFFSET(C2S_MatchRequest, _impl_.player_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void C2S_MatchRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.C2S_MatchRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.player_id_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL C2S_MatchRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const C2S_MatchRequest& this_ = static_cast<const C2S_MatchRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL C2S_MatchRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const C2S_MatchRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.C2S_MatchRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 player_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_player_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_player_id(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.C2S_MatchRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t C2S_MatchRequest::ByteSizeLong(const MessageLite& base) {
  const C2S_MatchRequest& this_ = static_cast<const C2S_MatchRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t C2S_MatchRequest::ByteSizeLong() const {
  const C2S_MatchRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Protocol.C2S_MatchRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int32 player_id = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_player_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_player_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void C2S_MatchRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<C2S_MatchRequest*>(&to_msg);
  auto& from = static_cast<const C2S_MatchRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.C2S_MatchRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (from._internal_player_id() != 0) {
      _this->_impl_.player_id_ = from._impl_.player_id_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void C2S_MatchRequest::CopyFrom(const C2S_MatchRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Protocol.C2S_MatchRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void C2S_MatchRequest::InternalSwap(C2S_MatchRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.player_id_, other->_impl_.player_id_);
}

::google::protobuf::Metadata C2S_MatchRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class S2C_MatchSuccess::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<S2C_MatchSuccess>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(S2C_MatchSuccess, _impl_._has_bits_);
};

S2C_MatchSuccess::S2C_MatchSuccess(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, S2C_MatchSuccess_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.S2C_MatchSuccess)
}
PROTOBUF_NDEBUG_INLINE S2C_MatchSuccess::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Protocol::S2C_MatchSuccess& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        ds_ip_(arena, from.ds_ip_) {}

S2C_MatchSuccess::S2C_MatchSuccess(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const S2C_MatchSuccess& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, S2C_MatchSuccess_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  S2C_MatchSuccess* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.ds_port_ = from._impl_.ds_port_;

  // @@protoc_insertion_point(copy_constructor:Protocol.S2C_MatchSuccess)
}
PROTOBUF_NDEBUG_INLINE S2C_MatchSuccess::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        ds_ip_(arena) {}

inline void S2C_MatchSuccess::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.ds_port_ = {};
}
S2C_MatchSuccess::~S2C_MatchSuccess() {
  // @@protoc_insertion_point(destructor:Protocol.S2C_MatchSuccess)
  SharedDtor(*this);
}
inline void S2C_MatchSuccess::SharedDtor(MessageLite& self) {
  S2C_MatchSuccess& this_ = static_cast<S2C_MatchSuccess&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.ds_ip_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL S2C_MatchSuccess::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) S2C_MatchSuccess(arena);
}
constexpr auto S2C_MatchSuccess::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(S2C_MatchSuccess),
                                            alignof(S2C_MatchSuccess));
}
constexpr auto S2C_MatchSuccess::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_S2C_MatchSuccess_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &S2C_MatchSuccess::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<S2C_MatchSuccess>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &S2C_MatchSuccess::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<S2C_MatchSuccess>(), &S2C_MatchSuccess::ByteSizeLong,
              &S2C_MatchSuccess::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(S2C_MatchSuccess, _impl_._cached_size_),
          false,
      },
      &S2C_MatchSuccess::kDescriptorMethods,
      &descriptor_table_Protocol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull S2C_MatchSuccess_class_data_ =
        S2C_MatchSuccess::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
S2C_MatchSuccess::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&S2C_MatchSuccess_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(S2C_MatchSuccess_class_data_.tc_table);
  return S2C_MatchSuccess_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 39, 2>
S2C_MatchSuccess::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(S2C_MatchSuccess, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    S2C_MatchSuccess_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::S2C_MatchSuccess>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 ds_port = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(S2C_MatchSuccess, _impl_.ds_port_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(S2C_MatchSuccess, _impl_.ds_port_)}},
    // string ds_ip = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(S2C_MatchSuccess, _impl_.ds_ip_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string ds_ip = 1;
    {PROTOBUF_FIELD_OFFSET(S2C_MatchSuccess, _impl_.ds_ip_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 ds_port = 2;
    {PROTOBUF_FIELD_OFFSET(S2C_MatchSuccess, _impl_.ds_port_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\31\5\0\0\0\0\0\0"
    "Protocol.S2C_MatchSuccess"
    "ds_ip"
  }},
};
PROTOBUF_NOINLINE void S2C_MatchSuccess::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.S2C_MatchSuccess)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.ds_ip_.ClearNonDefaultToEmpty();
  }
  _impl_.ds_port_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL S2C_MatchSuccess::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const S2C_MatchSuccess& this_ = static_cast<const S2C_MatchSuccess&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL S2C_MatchSuccess::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const S2C_MatchSuccess& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.S2C_MatchSuccess)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string ds_ip = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_ds_ip().empty()) {
      const ::std::string& _s = this_._internal_ds_ip();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Protocol.S2C_MatchSuccess.ds_ip");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // int32 ds_port = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_ds_port() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_ds_port(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.S2C_MatchSuccess)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t S2C_MatchSuccess::ByteSizeLong(const MessageLite& base) {
  const S2C_MatchSuccess& this_ = static_cast<const S2C_MatchSuccess&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t S2C_MatchSuccess::ByteSizeLong() const {
  const S2C_MatchSuccess& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Protocol.S2C_MatchSuccess)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string ds_ip = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_ds_ip().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_ds_ip());
      }
    }
    // int32 ds_port = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_ds_port() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_ds_port());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void S2C_MatchSuccess::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<S2C_MatchSuccess*>(&to_msg);
  auto& from = static_cast<const S2C_MatchSuccess&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.S2C_MatchSuccess)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_ds_ip().empty()) {
        _this->_internal_set_ds_ip(from._internal_ds_ip());
      } else {
        if (_this->_impl_.ds_ip_.IsDefault()) {
          _this->_internal_set_ds_ip("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_ds_port() != 0) {
        _this->_impl_.ds_port_ = from._impl_.ds_port_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void S2C_MatchSuccess::CopyFrom(const S2C_MatchSuccess& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Protocol.S2C_MatchSuccess)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void S2C_MatchSuccess::InternalSwap(S2C_MatchSuccess* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ds_ip_, &other->_impl_.ds_ip_, arena);
  swap(_impl_.ds_port_, other->_impl_.ds_port_);
}

::google::protobuf::Metadata S2C_MatchSuccess::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_Protocol_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
